// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEJlXTsOM4FFYJcdGUsJjH9fLtxV0pcY',
    appId: '1:473836464312:web:dfa6281d02385d69632c4d',
    messagingSenderId: '473836464312',
    projectId: 'uber-408815',
    authDomain: 'uber-408815.firebaseapp.com',
    storageBucket: 'uber-408815.appspot.com',
    measurementId: 'G-770SJJ8G9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_QKzG6wLQIL2E96ZtzD7q5d_EGkzVsIw',
    appId: '1:473836464312:android:1d5c3a047dd2857f632c4d',
    messagingSenderId: '473836464312',
    projectId: 'uber-408815',
    storageBucket: 'uber-408815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhT7Ja7eTCBvfy1yBhP5xpvH14fesrpFI',
    appId: '1:473836464312:ios:b034dee3b90a7c30632c4d',
    messagingSenderId: '473836464312',
    projectId: 'uber-408815',
    storageBucket: 'uber-408815.appspot.com',
    iosBundleId: 'com.example.softwareProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhT7Ja7eTCBvfy1yBhP5xpvH14fesrpFI',
    appId: '1:473836464312:ios:ae89786bd2cbe468632c4d',
    messagingSenderId: '473836464312',
    projectId: 'uber-408815',
    storageBucket: 'uber-408815.appspot.com',
    iosBundleId: 'com.example.softwareProject.RunnerTests',
  );
}
